/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserPreferences = IDL.Record({
  'userName' : IDL.Text,
  'voiceSpeed' : IDL.Float64,
  'assistantName' : IDL.Text,
});
export const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearConversationHistory' : IDL.Func([], [], []),
  'getAllUserPrefs' : IDL.Func([], [IDL.Vec(UserPreferences)], ['query']),
  'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOpenAIKey' : IDL.Func([], [IDL.Text], ['query']),
  'getUserPrefs' : IDL.Func([], [UserPreferences], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
  'sendOpenAIRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUserPrefs' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserPreferences = IDL.Record({
    'userName' : IDL.Text,
    'voiceSpeed' : IDL.Float64,
    'assistantName' : IDL.Text,
  });
  const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearConversationHistory' : IDL.Func([], [], []),
    'getAllUserPrefs' : IDL.Func([], [IDL.Vec(UserPreferences)], ['query']),
    'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOpenAIKey' : IDL.Func([], [IDL.Text], ['query']),
    'getUserPrefs' : IDL.Func([], [UserPreferences], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
    'sendOpenAIRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUserPrefs' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };